# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 09:38
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('question', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('kind', models.CharField(choices=[('MCQ', 'MCQ'), ('PARAGRAPH', 'PARAGRAPH')], max_length=15)),
                ('required', models.BooleanField(default=False)),
                ('paragraph', models.TextField(blank=True)),
                ('choices', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
                ('correct_choices', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), blank=True, null=True, size=None)),
            ],
            options={
                'verbose_name': 'Questionnaire',
                'verbose_name_plural': 'Questionnaires',
                'db_table': 'questionnaire_questionnaire',
            },
        ),
    ]
