# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20170616_1554'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
