# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 07:26
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('kind', models.CharField(choices=[('EVENT', 'EVENT'), ('SESSION', 'SESSION'), ('MEETUP', 'MEETUP'), ('CONFERENCE', 'CONFERENCE'), ('TALK', 'TALK'), ('WORKSHOP', 'WORKSHOP'), ('DEV_SPRINT', 'DEV SPRINT'), ('PANEL_DISCUSSION', 'PANEL DISCUSSION')], max_length=15)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concourse.Concourse')),
            ],
            options={
                'verbose_name': 'Concourse',
                'verbose_name_plural': 'Concourses',
                'db_table': 'concourse_concourse',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('kind', models.CharField(choices=[('HOST', 'HOST'), ('SPONSOR', 'SPONSOR'), ('OTHER', 'OTHER')], max_length=15)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organisation_organisation',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('about', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'concourse_speaker',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('concourse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concourse.Concourse')),
                ('organisation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concourse.Organisation')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'db_table': 'concourse_sponsor',
            },
        ),
    ]
