# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 07:28
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('kind', models.CharField(choices=[('EVENT', 'EVENT'), ('SESSION', 'SESSION'), ('MEETUP', 'MEETUP'), ('CONFERENCE', 'CONFERENCE'), ('TALK', 'TALK'), ('WORKSHOP', 'WORKSHOP'), ('DEV_SPRINT', 'DEV SPRINT'), ('PANEL_DISCUSSION', 'PANEL DISCUSSION')], max_length=15)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concourse.Concourse')),
            ],
            options={
                'verbose_name': 'Concourse',
                'verbose_name_plural': 'Concourses',
                'db_table': 'concourse_concourse',
            },
        ),
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('kind', models.CharField(choices=[('HOST', 'HOST'), ('SPONSOR', 'SPONSOR'), ('OTHER', 'OTHER')], max_length=15)),
            ],
            options={
                'verbose_name': 'Organisation',
                'verbose_name_plural': 'Organisations',
                'db_table': 'organisation_organisation',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(blank=True, max_length=120, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=120, verbose_name='Last Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('about', models.TextField(max_length=10000)),
            ],
            options={
                'verbose_name': 'Speaker',
                'verbose_name_plural': 'Speakers',
                'db_table': 'concourse_speaker',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'db_table': 'concourse_sponsor',
            },
        ),
        migrations.CreateModel(
            name='SponsorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Sponsor Category',
                'verbose_name_plural': 'Sponsor Categories',
                'db_table': 'concourse_sponsor_category',
            },
        ),
        migrations.AddField(
            model_name='sponsor',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concourse.SponsorCategory'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='concourse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='concourse.Concourse'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='concourse.Organisation'),
        ),
        migrations.AddField(
            model_name='concourse',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='concourses', to='concourse.Speaker'),
        ),
    ]
